---
# tasks file for openbao

- name: Import assert.yml
  ansible.builtin.import_tasks:
    file: assert.yml
  run_once: true
  delegate_to: localhost

- name: Ensure download directory exists
  ansible.builtin.file:
    path: "{{ openbao_download_dir }}"
    state: directory
    owner: root
    group: root
    mode: "{{ openbao_download_dir_mode }}"

- name: Download OpenBao GPG key
  ansible.builtin.get_url:
    url: "{{ openbao_gpg_key_url }}"
    dest: "{{ openbao_gpg_key_path }}"
    mode: "0644"
    validate_certs: "{{ openbao_validate_certs }}"
  when:
    - ansible_facts['pkg_mgr'] in [ "dnf", "dnf5", "yum" ]

- name: Import OpenBao GPG key (dnf/dnf5/yum)
  ansible.builtin.rpm_key:
    key: "{{ openbao_gpg_key_path }}"
    state: present
  when:
    - ansible_facts['pkg_mgr'] in [ "dnf", "dnf5", "yum" ]

- name: Configure OpenBao APT repository
  ansible.builtin.include_tasks:
    file: "{{ openbao_apt_repository_tasks }}"
  when:
    - ansible_facts['pkg_mgr'] == "apt"

- name: Configure OpenBao YUM repository
  ansible.builtin.yum_repository:
    name: openbao
    description: OpenBao repository
    baseurl: "{{ openbao_yum_repository_baseurl }}"
    gpgcheck: "{{ openbao_yum_repository_gpgkey | length > 0 }}"
    gpgkey: "{{ openbao_yum_repository_gpgkey | default(omit) }}"
    enabled: true
  when:
    - ansible_facts['pkg_mgr'] in [ "dnf", "dnf5", "yum" ]

- name: Install OpenBao package
  ansible.builtin.package:
    name: "{{ openbao_package_name }}"
    state: present
