---
- name: Converge
  hosts: all
  become: true
  gather_facts: true

  roles:
    - role: robertdebock.openbao
      openbao_storage:
        type: raft
        path: /opt/openbao/data
        node_id: node1
        retry_join:
          - leader_api_addr: "http://127.0.0.2:8200"
      openbao_cluster_addr: "https://127.0.0.1:8201"
      openbao_api_addr: "https://127.0.0.1:8200"
      openbao_listeners:
        - name: tcp
          address: "127.0.0.1:8200"
          tls_disable: true
      openbao_telemetry:
        prometheus_retention_time: "30s"
        disable_hostname: true
      openbao_log_requests_level: "info"
      openbao_audit_devices:
        - type: file
          path: "audit"
          description: "Audit logs to file"
          options:
            file_path: "/openbao/logs/audit.log"
            log_raw: false
      openbao_seal:
        - name: static
          current_key_id: "20250606-1"
          current_key: "file:///openbao/secrets/unseal-20250606-1.key"
      # Install plugin binaries
      openbao_plugin_directory: "/opt/openbao/plugins"
      openbao_plugins:
        - name: openbao-plugin-auth-aws
          version: "0.1.0"
          download_url: https://github.com/openbao/openbao-plugins/releases/download/auth-aws-v0.1.0/openbao-plugin-auth-aws_linux_amd64_v1.tar.gz
        - name: openbao-plugin-secrets-aws
          version: "0.1.0"
          download_url: https://github.com/openbao/openbao-plugins/releases/download/secrets-aws-v0.1.0/openbao-plugin-secrets-aws_linux_amd64_v1.tar.gz
      openbao_plugin_cleanup: false
