---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Check if connection still works
      ansible.builtin.ping:

    - name: Verify OpenBao binary works
      ansible.builtin.command: bao --version
      changed_when: false
