---
- name: Verify
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Check if connection still works
      ansible.builtin.ping:

    - name: Verify OpenBao binary works
      ansible.builtin.command: bao --version
      changed_when: false

    - name: Initialize OpenBao
      ansible.builtin.command: bao operator init
      environment:
        BAO_ADDR: http://127.0.0.1:8200
      changed_when: true
